name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
        description: Provide the ingress URL
        required: true
        type: string  
    
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ APP_INGRESS_URL }}'          
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live
