name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs: 
      ingress-url:
        Input-id: tester
        description: Provide the Ingress URLs
        required: true
        type: string
        
      
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ inputs.igress-url }}'
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live
